### ISSUE TITLE
add Module Name in Directory Path - 폴더 경로 표시

### ISSUE THREAD

**Issue by jongkyungbyun** [1434cga/CGA_RDL#3]
I wanna change the Directory Path including module name. (ex. include/DiagManagerService/)
(어떻게 변경해야 하나요? 소스는 git에  올려 놓았습니다.)

stcI_HASH : Module_Name
stcI_EXTENSION : h
stcI_FILEPREFIX : include/+<+$MODULENAME+>+ManagerService/
stcI_FILEPOSTFIX : Command
Set : $iterate_comments = OFF
SetI : $MODULENAME = KEY

**Comment by cheoljoo** [comment]
Solved it.  #4

**Comment by cheoljoo** [comment]
- example 2 (test/DIAG/IXXXManagerService.cpp.stcI)
Module_Name has 2 keys : Diag and Antenna
stcI_HASH : Module_Name
stcI_EXTENSION : h
stcI_FILEPREFIX : TTTKEY/I
stcI_FILEPOSTFIX : ManagerService
Set : $iterate_comments = OFF
SetI : $MODULENAME = KEY
- output :
OUTPUT/stc/TTTDiag/IDiagManagerService.h
OUTPUT/stc/TTTAntenna/IAntennaManagerService.h
