### ISSUE TITLE
showing 65280 instead of system

### ISSUE THREAD

**Issue by jongkyungbyun** [1434cga/CGA_RDL#5]
when it is generated, 

65280 is showing instead of system.

expected message : 

MSG_CONNECT_TO_SYSTEMMGR ,
MSG_RECEIVE_FROM_SYSTEM ,

Result

MSG_CONNECT_TO_65280MGR ,
MSG_RECEIVE_FROM_65280

**Comment by cheoljoo** [comment]
use +<+uc("ITKEY")+>+  instread of +<+uc(ITKEY)+>+   bacause system is special commands. 
you can use as string to add " "
